### PR TITLE
Adds 1 video, fixes another

### PR DESCRIPTION
**Pull request by jkmcclellan**

### CODE REVIEW

**Review by MaureenElsberry — APPROVED** [review]
Thanks, Jason - have the Arrow KotlinDevDay talks been added? I think there is a total of 4

**Comment by jkmcclellan** [comment]
We added the link to the post we did on 47 (https://www.47deg.com/blog/arrow-put-on-big-show-at-kotlindevday/)

**Comment by MaureenElsberry** [comment]
Ok, we may want to individually add the videos as well

**Comment by jkmcclellan** [comment]
Sure thing! I'll make sure that gets taken care of.

**Pull request merged**
